version: '3.5'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kafka-demo-network
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    networks:
      - kafka-demo-network
    ports:
      - 9092:9092
    expose:
      - 29092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    networks:
      - kafka-demo-network
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo -e 'Waiting for Kafka start ...'
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Creating Kafka topic ...'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic demo-topic --replication-factor 1 --partitions 2

      echo -e 'Kafka topic was created successfully'
      kafka-topics --bootstrap-server kafka:29092 --list
      "

networks:
  kafka-demo-network:
    name: kafka-demo-network
    driver: bridge
